-- Family Ledger: H1 -- payment allocation window becomes the period's whole
-- month.
--
-- Replaces the body of public.payment_period_status(p_period_id) (first
-- defined in 20260905060000_payment_period_status.sql -- read that header for
-- the full design: return shape, SECURITY INVOKER rationale, status
-- precedence, the due-date boundary, and the household-time-zone "today").
-- Everything in that design is unchanged here EXCEPT the allocation window.
-- This function remains the ONE canonical implementation of the section 7.3
-- allocation rule; nothing else should reimplement it.
--
-- Old rule (20260905060000): a payment counted toward a period only when
--   occurred_on > period_start and occurred_on <= due_date.
-- That window left gaps. A payment dated ON period_start (e.g. a $30 payment
-- on Oct 1 against an October period starting Oct 1), or dated after
-- due_date but before the next period began (a late payment), counted toward
-- NO period at all -- the period kept reading "$0.00 of $25.00 paid" /
-- 'overdue' even though the child had paid.
--
-- New rule (owner decision, 2026-10-03): a payment counts toward the period
-- whose month it falls in:
--   occurred_on >= period_start and occurred_on < next_period_start
-- where next_period_start is the date the plan's following period starts on.
-- Consecutive periods' windows therefore tile the calendar with no gap and no
-- overlap: every payment date belongs to exactly one period of the plan.
-- Late payments (after due_date, before the next period starts) still count
-- toward their own month, so paying the minimum late turns an 'overdue'
-- period 'satisfied' -- consistent with the existing precedence, which
-- already checks satisfied before overdue.
--
-- Unchanged allocation conditions: type = 'payment' only (never 'expense' or
-- 'adjustment'), voided_at is null, same member_id as the period, and
-- paid_cents is the negated sum (payments are stored negative).
--
-- How next_period_start is computed. Periods are generated by
-- ensure_current_payment_period (20260905050000) at
--   period_start = plan.starts_on + N months
-- always anchored to the ORIGINAL starts_on (never compounded), because
-- Postgres clamps month arithmetic at month end ('2025-01-31' + 1 month =
-- '2025-02-28'), so compounding would drift a 31st anchor to the 28th
-- forever. next_period_start must use the same anchoring, so it is defined
-- as: the smallest (plan.starts_on + k months), over integer k, that is
-- strictly greater than this period's period_start. Concretely:
--   m := whole calendar months from starts_on's month to period_start's
--        month (year*12 + month difference);
--   starts_on + m months always lands in period_start's own calendar month
--   (clamped to that month's last day if needed), and starts_on + (m-1)
--   months lands in the previous month, so the answer is
--     starts_on + m months      if that is > period_start, else
--     starts_on + (m+1) months.
-- For every period ensure_current_payment_period generates (period_start =
-- starts_on + m months exactly) this is starts_on + (m+1) months -- e.g.
-- starts_on Jan 31 gives periods Jan 31, Feb 28, Mar 31, and the Feb window
-- is [Feb 28, Mar 31). It is also well-defined for any other period_start
-- (e.g. a hand-inserted test row not on the anchor grid): the window then
-- runs to the next anchor date after it. plan.ends_on is deliberately
-- ignored: the last period of an ended plan still owns its whole month.
--
-- Authorization is unchanged: still SECURITY INVOKER, so every lookup runs as
-- the caller under RLS. This version additionally reads public.payment_plans
-- (for starts_on), joined via payment_periods.payment_plan_id. That does not
-- widen anything: payment_plans_select_parent / payment_plans_select_self
-- (20260905040000) mirror payment_periods_select_parent / _self exactly --
-- a Parent sees every plan in their household, a Child sees plans whose
-- member_id is their own -- and a period's household_id/member_id are copied
-- from its plan when the period is generated. So any caller who can see a
-- period can also see its plan; no SECURITY DEFINER is needed. (Covered by
-- 005_payment_plans_privilege_escalation.sql, which calls this function as
-- the Child as well as the Parent.)

create or replace function public.payment_period_status(p_period_id uuid)
returns table (
  period_id uuid,
  status text,
  minimum_cents bigint,
  paid_cents bigint,
  remaining_cents bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
  with period as (
    -- RLS-respecting lookups (SECURITY INVOKER): payment_periods,
    -- payment_plans and households SELECT policies all apply exactly as they
    -- would to a hand-written query. An unauthorized p_period_id produces
    -- zero rows here, and therefore zero rows from the whole function.
    select
      pp.id,
      pp.member_id,
      pp.period_start,
      pp.due_date,
      pp.minimum_cents,
      pp.waived_at,
      h.timezone,
      pl.starts_on,
      (
        (extract(year from pp.period_start) - extract(year from pl.starts_on)) * 12
        + (extract(month from pp.period_start) - extract(month from pl.starts_on))
      )::integer as months_from_start
    from public.payment_periods pp
    join public.payment_plans pl on pl.id = pp.payment_plan_id
    join public.households h on h.id = pp.household_id
    where pp.id = p_period_id
  ),
  bounds as (
    -- next_period_start: the smallest starts_on + k months strictly after
    -- period_start (see header). Anchored to starts_on, never compounded.
    select
      p.*,
      case
        when (p.starts_on + make_interval(months => p.months_from_start))::date > p.period_start
          then (p.starts_on + make_interval(months => p.months_from_start))::date
        else (p.starts_on + make_interval(months => p.months_from_start + 1))::date
      end as next_period_start
    from period p
  ),
  paid as (
    -- The one canonical implementation of the section 7.3 allocation rule:
    -- the period's whole month, [period_start, next_period_start).
    select
      coalesce(sum(-lt.amount_cents), 0)::bigint as paid_cents
    from bounds b
    join public.ledger_transactions lt
      on lt.member_id = b.member_id
     and lt.type = 'payment'
     and lt.voided_at is null
     and lt.occurred_on >= b.period_start
     and lt.occurred_on < b.next_period_start
  ),
  today as (
    select (now() at time zone b.timezone)::date as today
    from bounds b
  )
  select
    b.id as period_id,
    case
      when b.waived_at is not null then 'waived'
      when pd.paid_cents >= b.minimum_cents then 'satisfied'
      when t.today > b.due_date then 'overdue'
      when pd.paid_cents > 0 then 'partially_paid'
      when t.today >= b.period_start then 'due'
      else 'upcoming'
    end as status,
    b.minimum_cents,
    pd.paid_cents,
    (b.minimum_cents - pd.paid_cents) as remaining_cents
  from bounds b
  cross join paid pd
  cross join today t;
$$;

comment on function public.payment_period_status(uuid) is
  'Derive one of upcoming/due/partially_paid/satisfied/overdue/waived for a payment_periods row, plus paid_cents/remaining_cents. The single canonical implementation of the section 7.3 payment-allocation rule and status precedence. Allocation: a non-voided payment by the period''s member counts toward the period whose month it falls in -- occurred_on >= period_start and occurred_on < next_period_start, where next_period_start is the plan''s following period start (smallest plan.starts_on + k months after period_start, anchored to starts_on like ensure_current_payment_period). Replaced the earlier (period_start, due_date] window, which left gaps: payments on period_start or after due_date counted toward no period; month windows tile with no gap or overlap. See migrations 20260905060000 and 20261003090000 for the full design. SECURITY INVOKER: runs as the caller so payment_periods/payment_plans/households RLS SELECT policies apply, returning zero rows for a period the caller cannot see.';

-- create or replace keeps the existing ACL, but re-assert the same explicit
-- revoke/grant pattern as 20260905060000 so this file is self-describing.
revoke execute on function public.payment_period_status(uuid) from public, anon;
grant execute on function public.payment_period_status(uuid) to authenticated;
